package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "effects",
    srcs = ["effects.cpp"],
    hdrs = ["effects.h"],
    deps = [
        "@spline",
    ],
)

cc_test(
    name = "effects_test",
    srcs = ["effects_test.cpp"],
    deps = [
        ":effects",
        "@gtest//:gtest_main",
    ],
)

cc_library(
    name = "continuous_noise",
    srcs = ["continuous_noise.cpp"],
    hdrs = ["continuous_noise.h"],
    deps = [
        "@world",
    ],
)

cc_test(
    name = "continuous_noise_test",
    srcs = ["continuous_noise_test.cpp"],
    deps = [
        ":continuous_noise",
        "@gtest//:gtest_main",
    ],
)
