package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "effects",
    srcs = ["effects.cpp"],
    hdrs = ["effects.h"],
    deps = [
        "@spline",
    ],
)

cc_library(
    name = "model",
    srcs = ["model.cpp"],
    hdrs = ["model.h"],
    deps = [
        "//worldline/common:vec_utils",
        "//worldline/f0",
        "@world",
    ],
)

cc_test(
    name = "effects_test",
    srcs = ["effects_test.cpp"],
    deps = [
        ":effects",
        "@gtest//:gtest_main",
    ],
)
